apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-database
  template:
    metadata:
      labels:
        app: myapp-database
    spec:
      containers:
      - name: myapp-database
        image: eklavya163940/myapp-database:latest
        ports:
        - containerPort: 5432
        