apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-processing-deployment
  labels:
    app: order-processing
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-processing
  template:
    metadata:
      labels:
        app: order-processing
    spec:
      containers:
        - name: order-processing
          image: eklavya163940/order-processing:v1
          ports:
           - containerPort: 80


        
    